// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6iW_MObTvE0QgNJzvLyDIj-f5fVFuf7g',
    appId: '1:405982975042:web:221d79ba0ff990e1ca09db',
    messagingSenderId: '405982975042',
    projectId: 'mobile2-86c10',
    authDomain: 'mobile2-86c10.firebaseapp.com',
    storageBucket: 'mobile2-86c10.appspot.com',
    measurementId: 'G-M2QQPE4TYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrD51eOvzjA-CKmYsmT0pR9u1eNx-c3T4',
    appId: '1:405982975042:android:310d8dd67be24c1bca09db',
    messagingSenderId: '405982975042',
    projectId: 'mobile2-86c10',
    storageBucket: 'mobile2-86c10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLznmIzlA0aqrnQIFRLMkjX6xgbUgpuDk',
    appId: '1:405982975042:ios:411bef14a8d7f44bca09db',
    messagingSenderId: '405982975042',
    projectId: 'mobile2-86c10',
    storageBucket: 'mobile2-86c10.appspot.com',
    iosBundleId: 'com.example.codelab',
  );
}
